---
- hosts: servers
  become_user: root
  become: yes
  tasks:
  - name: install httpd
    yum: name=httpd state=latest

  - name: start httpd service
    service: name=httpd state=started

  - name: Install mysqpl repo
    shell: rpm -Uvh https://dev.mysql.com/get/mysql57-community-release-el7-7.noarch.rpm
    args:
      creates: /etc/yum.repos.d/mysql-community.repo

  - name: insall mysql
    yum:  name=mysql-server state=latest

  handlers:
  - name: restart httpd
    service: name=httpd state=restarted
  - name: restart mysql
    service: name=mysqld state=restarted
